In [1]:
# _____________________________ REVENUE PREDICTION ____________________________

# Import Libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Import Machine Learning LIbraries

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import LabelEncoder

# Load Dataset

In [4]:
df = pd.read_csv('revenue_prediction.csv')

# Explore Data

In [5]:
df.head()

,Id,Name,Franchise,Category,City,No_Of_Item,Order_Placed,Revenue
0,101,HungryHowie'sPizza,Yes,Mexican,Bengaluru,55,5.5,5953753
1,102,CharleysPhillySteaks,No,Varied Menu,Gurugram,72,6.8,7223131
2,103,Chuy's,Yes,Chicken,Pune,25,1.9,2555379
3,104,O'Charley's,Yes,Italian/Pizza,Mumbai,18,2.5,2175511
4,105,PolloTropical,Yes,Pizza,Noida,48,4.2,4816715

In [6]:
df.isnull().sum().sum()

np.int64(0)

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.columns

Index(['Id', 'Name', 'Franchise', 'Category', 'City', 'No_Of_Item',
       'Order_Placed', 'Revenue'],
      dtype='object')

In [9]:
df.shape

(100, 8)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            100 non-null    int64
 1   Name          100 non-null    object
 2   Franchise     100 non-null    object
 3   Category      100 non-null    object
 4   City          100 non-null    object
 5   No_Of_Item    100 non-null    int64
 6   Order_Placed  100 non-null    float64
 7   Revenue       100 non-null    int64
dtypes: float64(1), int64(3), object(4)
memory usage: 6.4+ KB

In [11]:
df.describe()

               Id  No_Of_Item  Order_Placed       Revenue
count  100.000000  100.000000    100.000000  1.000000e+02
mean   150.500000   49.080000      4.086000  4.395161e+06
std     29.011492   22.370923      2.055101  2.659932e+06
min    101.000000   18.000000      1.000000  8.498700e+05
25%    125.750000   34.750000      2.750000  2.688328e+06
50%    150.500000   45.000000      3.650000  3.911401e+06
75%    175.250000   57.250000      5.100000  5.330084e+06
max    200.000000  126.000000     13.000000  1.969694e+07

In [12]:
df.dtypes

Id                int64
Name             object
Franchise        object
Category         object
City             object
No_Of_Item        int64
Order_Placed    float64
Revenue           int64
dtype: object

In [13]:
df["Franchise"].value_counts()
df["Category"].value_counts()

Category
Varied Menu        16
Mexican            10
Pizza               9
Italian/Pizza       7
Family Style        7
Steak               7
Sandwich            7
Burger              7
Bakery Cafe         5
BBQ                 4
Seafood             4
Family Casual       3
Chicken             2
Frozen Desserts     2
Coffee Cafe         2
Sports Bar          2
Snack               2
Asian/Noodle        2
Asian               1
Healthy             1
Name: count, dtype: int64

In [14]:
df = pd.get_dummies(df,columns=["Franchise", "Category"], drop_first = True)

In [15]:
df = pd.get_dummies(df,columns=["City"], drop_first = True)

In [16]:
x = df.drop(["Revenue", "Name"], axis=1)
y = df["Revenue"]

In [17]:
x.dtypes

Id                            int64
No_Of_Item                    int64
Order_Placed                float64
Franchise_Yes                  bool
Category_Asian/Noodle          bool
Category_BBQ                   bool
Category_Bakery Cafe           bool
Category_Burger                bool
Category_Chicken               bool
Category_Coffee Cafe           bool
Category_Family Casual         bool
Category_Family Style          bool
Category_Frozen Desserts       bool
Category_Healthy               bool
Category_Italian/Pizza         bool
Category_Mexican               bool
Category_Pizza                 bool
Category_Sandwich              bool
Category_Seafood               bool
Category_Snack                 bool
Category_Sports Bar            bool
Category_Steak                 bool
Category_Varied Menu           bool
City_Gurugram                  bool
City_Mumbai                    bool
City_Noida                     bool
City_Pune                      bool
dtype: object

In [18]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 42)

In [19]:
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [20]:
y_pred = model.predict(x_test)

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae = mean_absolute_error(y_test,y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("R2 Score:", r2)

In [21]:
result  = pd.DataFrame({
      "Actual Revenue" : y_test.values,
      "Predicted Revenue": y_pred
})

result.head(10)

   Actual Revenue  Predicted Revenue
0         5966193       4.655797e+06
1         5595267       5.750071e+06
2         3982767       3.595709e+06
3         3752885       5.301685e+06
4         4264176       4.698755e+06
5         3818055       3.660950e+06
6         4956086       3.558481e+06
7         3727364       3.258452e+06
8         3945135       3.987843e+06
9         5953753       6.665329e+06

# Conclusion:

In this project, a machine learning model was developed to predict restaurant revenue based on the available restaurant features. The dataset was cleaned and preprocessed, including handling categorical variables using encoding techniques. The relevant features were selected and the data was divided into training and testing sets.

A Linear Regression model was trained to predict restaurant revenue. The model's performance was evaluated using MAE, MSE, and R² score. The results demonstrate how machine learning can be used to understand the relationship between restaurant characteristics, order volume, and revenue.

Overall, this project provided practical experience in data preprocessing, exploratory analysis, feature encoding, model building, prediction, and model evaluation using Python and Scikit-learn.